package com.artwook.nft.nftshop.db.mapper;

import com.artwook.nft.nftshop.db.model.Attachments;
import com.artwook.nft.nftshop.db.model.AttachmentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttachmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int countByExample(AttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByExample(AttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insert(Attachments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insertSelective(Attachments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    List<Attachments> selectByExample(AttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    Attachments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") Attachments record, @Param("example") AttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExample(@Param("record") Attachments record, @Param("example") AttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKeySelective(Attachments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKey(Attachments record);
}