package com.artwook.nft.nftshop.db.mapper;

import com.artwook.nft.nftshop.db.model.DailyRecord;
import com.artwook.nft.nftshop.db.model.DailyRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DailyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int countByExample(DailyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByExample(DailyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insert(DailyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insertSelective(DailyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    List<DailyRecord> selectByExampleWithBLOBs(DailyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    List<DailyRecord> selectByExample(DailyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    DailyRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") DailyRecord record, @Param("example") DailyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") DailyRecord record, @Param("example") DailyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExample(@Param("record") DailyRecord record, @Param("example") DailyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKeySelective(DailyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(DailyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKey(DailyRecord record);
}