package com.artwook.nft.nftshop.db.mapper;

import com.artwook.nft.nftshop.db.model.Dictionary;
import com.artwook.nft.nftshop.db.model.DictionaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int countByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insertSelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    List<Dictionary> selectByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    Dictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") Dictionary record, @Param("example") DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExample(@Param("record") Dictionary record, @Param("example") DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dictionary
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKey(Dictionary record);
}