package com.artwook.nft.nftshop.db.mapper;

import com.artwook.nft.nftshop.db.model.MxRecord;
import com.artwook.nft.nftshop.db.model.MxRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MxRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int countByExample(MxRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByExample(MxRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insert(MxRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insertSelective(MxRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    List<MxRecord> selectByExample(MxRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    MxRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") MxRecord record, @Param("example") MxRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExample(@Param("record") MxRecord record, @Param("example") MxRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKeySelective(MxRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKey(MxRecord record);
}