package com.artwook.nft.nftshop.db.mapper;

import com.artwook.nft.nftshop.db.model.PathologyRecord;
import com.artwook.nft.nftshop.db.model.PathologyRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PathologyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int countByExample(PathologyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByExample(PathologyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insert(PathologyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insertSelective(PathologyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    List<PathologyRecord> selectByExampleWithBLOBs(PathologyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    List<PathologyRecord> selectByExample(PathologyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    PathologyRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") PathologyRecord record, @Param("example") PathologyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") PathologyRecord record, @Param("example") PathologyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExample(@Param("record") PathologyRecord record, @Param("example") PathologyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKeySelective(PathologyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(PathologyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pathology_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKey(PathologyRecord record);
}