package com.artwook.nft.nftshop.db.mapper;

import com.artwook.nft.nftshop.db.model.Patient;
import com.artwook.nft.nftshop.db.model.PatientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_patient
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int countByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_patient
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_patient
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_patient
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_patient
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int insertSelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_patient
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    List<Patient> selectByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_patient
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    Patient selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_patient
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_patient
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByExample(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_patient
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKeySelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_patient
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    int updateByPrimaryKey(Patient record);
}