package com.artwook.nft.nftshop.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AttachmentsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public AttachmentsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAttachUuidIsNull() {
            addCriterion("attach_uuid is null");
            return (Criteria) this;
        }

        public Criteria andAttachUuidIsNotNull() {
            addCriterion("attach_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andAttachUuidEqualTo(String value) {
            addCriterion("attach_uuid =", value, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andAttachUuidNotEqualTo(String value) {
            addCriterion("attach_uuid <>", value, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andAttachUuidGreaterThan(String value) {
            addCriterion("attach_uuid >", value, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andAttachUuidGreaterThanOrEqualTo(String value) {
            addCriterion("attach_uuid >=", value, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andAttachUuidLessThan(String value) {
            addCriterion("attach_uuid <", value, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andAttachUuidLessThanOrEqualTo(String value) {
            addCriterion("attach_uuid <=", value, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andAttachUuidLike(String value) {
            addCriterion("attach_uuid like", value, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andAttachUuidNotLike(String value) {
            addCriterion("attach_uuid not like", value, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andAttachUuidIn(List<String> values) {
            addCriterion("attach_uuid in", values, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andAttachUuidNotIn(List<String> values) {
            addCriterion("attach_uuid not in", values, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andAttachUuidBetween(String value1, String value2) {
            addCriterion("attach_uuid between", value1, value2, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andAttachUuidNotBetween(String value1, String value2) {
            addCriterion("attach_uuid not between", value1, value2, "attachUuid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andOssPathIsNull() {
            addCriterion("oss_path is null");
            return (Criteria) this;
        }

        public Criteria andOssPathIsNotNull() {
            addCriterion("oss_path is not null");
            return (Criteria) this;
        }

        public Criteria andOssPathEqualTo(String value) {
            addCriterion("oss_path =", value, "ossPath");
            return (Criteria) this;
        }

        public Criteria andOssPathNotEqualTo(String value) {
            addCriterion("oss_path <>", value, "ossPath");
            return (Criteria) this;
        }

        public Criteria andOssPathGreaterThan(String value) {
            addCriterion("oss_path >", value, "ossPath");
            return (Criteria) this;
        }

        public Criteria andOssPathGreaterThanOrEqualTo(String value) {
            addCriterion("oss_path >=", value, "ossPath");
            return (Criteria) this;
        }

        public Criteria andOssPathLessThan(String value) {
            addCriterion("oss_path <", value, "ossPath");
            return (Criteria) this;
        }

        public Criteria andOssPathLessThanOrEqualTo(String value) {
            addCriterion("oss_path <=", value, "ossPath");
            return (Criteria) this;
        }

        public Criteria andOssPathLike(String value) {
            addCriterion("oss_path like", value, "ossPath");
            return (Criteria) this;
        }

        public Criteria andOssPathNotLike(String value) {
            addCriterion("oss_path not like", value, "ossPath");
            return (Criteria) this;
        }

        public Criteria andOssPathIn(List<String> values) {
            addCriterion("oss_path in", values, "ossPath");
            return (Criteria) this;
        }

        public Criteria andOssPathNotIn(List<String> values) {
            addCriterion("oss_path not in", values, "ossPath");
            return (Criteria) this;
        }

        public Criteria andOssPathBetween(String value1, String value2) {
            addCriterion("oss_path between", value1, value2, "ossPath");
            return (Criteria) this;
        }

        public Criteria andOssPathNotBetween(String value1, String value2) {
            addCriterion("oss_path not between", value1, value2, "ossPath");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_attachment
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 15 23:49:30 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_attachment
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}