package com.artwook.nft.nftshop.db.model;

import java.util.Date;

public class Attachments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attachment.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attachment.attach_uuid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String attachUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attachment.type
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attachment.oss_path
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String ossPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attachment.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attachment.id
     *
     * @return the value of tb_attachment.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attachment.id
     *
     * @param id the value for tb_attachment.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attachment.attach_uuid
     *
     * @return the value of tb_attachment.attach_uuid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getAttachUuid() {
        return attachUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attachment.attach_uuid
     *
     * @param attachUuid the value for tb_attachment.attach_uuid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setAttachUuid(String attachUuid) {
        this.attachUuid = attachUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attachment.type
     *
     * @return the value of tb_attachment.type
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attachment.type
     *
     * @param type the value for tb_attachment.type
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attachment.oss_path
     *
     * @return the value of tb_attachment.oss_path
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getOssPath() {
        return ossPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attachment.oss_path
     *
     * @param ossPath the value for tb_attachment.oss_path
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setOssPath(String ossPath) {
        this.ossPath = ossPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attachment.created_at
     *
     * @return the value of tb_attachment.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attachment.created_at
     *
     * @param createdAt the value for tb_attachment.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}