package com.artwook.nft.nftshop.db.model;

import java.util.Date;

public class DailyRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_daily_record.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_daily_record.pid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_daily_record.record_date
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Date recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_daily_record.mx_id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String mxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_daily_record.diagnose
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String diagnose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_daily_record.prescription
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String prescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_daily_record.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_daily_record.user_id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_daily_record.mx_content
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String mxContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_daily_record.id
     *
     * @return the value of tb_daily_record.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_daily_record.id
     *
     * @param id the value for tb_daily_record.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_daily_record.pid
     *
     * @return the value of tb_daily_record.pid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_daily_record.pid
     *
     * @param pid the value for tb_daily_record.pid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_daily_record.record_date
     *
     * @return the value of tb_daily_record.record_date
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_daily_record.record_date
     *
     * @param recordDate the value for tb_daily_record.record_date
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_daily_record.mx_id
     *
     * @return the value of tb_daily_record.mx_id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getMxId() {
        return mxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_daily_record.mx_id
     *
     * @param mxId the value for tb_daily_record.mx_id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setMxId(String mxId) {
        this.mxId = mxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_daily_record.diagnose
     *
     * @return the value of tb_daily_record.diagnose
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getDiagnose() {
        return diagnose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_daily_record.diagnose
     *
     * @param diagnose the value for tb_daily_record.diagnose
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setDiagnose(String diagnose) {
        this.diagnose = diagnose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_daily_record.prescription
     *
     * @return the value of tb_daily_record.prescription
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getPrescription() {
        return prescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_daily_record.prescription
     *
     * @param prescription the value for tb_daily_record.prescription
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setPrescription(String prescription) {
        this.prescription = prescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_daily_record.created_at
     *
     * @return the value of tb_daily_record.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_daily_record.created_at
     *
     * @param createdAt the value for tb_daily_record.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_daily_record.user_id
     *
     * @return the value of tb_daily_record.user_id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_daily_record.user_id
     *
     * @param userId the value for tb_daily_record.user_id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_daily_record.mx_content
     *
     * @return the value of tb_daily_record.mx_content
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getMxContent() {
        return mxContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_daily_record.mx_content
     *
     * @param mxContent the value for tb_daily_record.mx_content
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setMxContent(String mxContent) {
        this.mxContent = mxContent;
    }
}