package com.artwook.nft.nftshop.db.model;

import java.util.Date;

public class Dictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary.dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer dicIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary.dic_name
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String dicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary.dic_key
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String dicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary.key_desc
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String keyDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary.value_type
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String valueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary.value_dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer valueDicIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dictionary.updated_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary.id
     *
     * @return the value of tb_dictionary.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary.id
     *
     * @param id the value for tb_dictionary.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary.dic_index
     *
     * @return the value of tb_dictionary.dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getDicIndex() {
        return dicIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary.dic_index
     *
     * @param dicIndex the value for tb_dictionary.dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setDicIndex(Integer dicIndex) {
        this.dicIndex = dicIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary.dic_name
     *
     * @return the value of tb_dictionary.dic_name
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getDicName() {
        return dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary.dic_name
     *
     * @param dicName the value for tb_dictionary.dic_name
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setDicName(String dicName) {
        this.dicName = dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary.dic_key
     *
     * @return the value of tb_dictionary.dic_key
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getDicKey() {
        return dicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary.dic_key
     *
     * @param dicKey the value for tb_dictionary.dic_key
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setDicKey(String dicKey) {
        this.dicKey = dicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary.key_desc
     *
     * @return the value of tb_dictionary.key_desc
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getKeyDesc() {
        return keyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary.key_desc
     *
     * @param keyDesc the value for tb_dictionary.key_desc
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setKeyDesc(String keyDesc) {
        this.keyDesc = keyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary.value_type
     *
     * @return the value of tb_dictionary.value_type
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getValueType() {
        return valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary.value_type
     *
     * @param valueType the value for tb_dictionary.value_type
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setValueType(String valueType) {
        this.valueType = valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary.value_dic_index
     *
     * @return the value of tb_dictionary.value_dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getValueDicIndex() {
        return valueDicIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary.value_dic_index
     *
     * @param valueDicIndex the value for tb_dictionary.value_dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setValueDicIndex(Integer valueDicIndex) {
        this.valueDicIndex = valueDicIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary.created_at
     *
     * @return the value of tb_dictionary.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary.created_at
     *
     * @param createdAt the value for tb_dictionary.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dictionary.updated_at
     *
     * @return the value of tb_dictionary.updated_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dictionary.updated_at
     *
     * @param updatedAt the value for tb_dictionary.updated_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}