package com.artwook.nft.nftshop.db.model;

import java.util.ArrayList;
import java.util.List;

public class MxRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public MxRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNull() {
            addCriterion("record_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNotNull() {
            addCriterion("record_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordIdEqualTo(String value) {
            addCriterion("record_id =", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotEqualTo(String value) {
            addCriterion("record_id <>", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThan(String value) {
            addCriterion("record_id >", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThanOrEqualTo(String value) {
            addCriterion("record_id >=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThan(String value) {
            addCriterion("record_id <", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThanOrEqualTo(String value) {
            addCriterion("record_id <=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLike(String value) {
            addCriterion("record_id like", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotLike(String value) {
            addCriterion("record_id not like", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdIn(List<String> values) {
            addCriterion("record_id in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotIn(List<String> values) {
            addCriterion("record_id not in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdBetween(String value1, String value2) {
            addCriterion("record_id between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotBetween(String value1, String value2) {
            addCriterion("record_id not between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andDicIndexIsNull() {
            addCriterion("dic_index is null");
            return (Criteria) this;
        }

        public Criteria andDicIndexIsNotNull() {
            addCriterion("dic_index is not null");
            return (Criteria) this;
        }

        public Criteria andDicIndexEqualTo(Integer value) {
            addCriterion("dic_index =", value, "dicIndex");
            return (Criteria) this;
        }

        public Criteria andDicIndexNotEqualTo(Integer value) {
            addCriterion("dic_index <>", value, "dicIndex");
            return (Criteria) this;
        }

        public Criteria andDicIndexGreaterThan(Integer value) {
            addCriterion("dic_index >", value, "dicIndex");
            return (Criteria) this;
        }

        public Criteria andDicIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("dic_index >=", value, "dicIndex");
            return (Criteria) this;
        }

        public Criteria andDicIndexLessThan(Integer value) {
            addCriterion("dic_index <", value, "dicIndex");
            return (Criteria) this;
        }

        public Criteria andDicIndexLessThanOrEqualTo(Integer value) {
            addCriterion("dic_index <=", value, "dicIndex");
            return (Criteria) this;
        }

        public Criteria andDicIndexIn(List<Integer> values) {
            addCriterion("dic_index in", values, "dicIndex");
            return (Criteria) this;
        }

        public Criteria andDicIndexNotIn(List<Integer> values) {
            addCriterion("dic_index not in", values, "dicIndex");
            return (Criteria) this;
        }

        public Criteria andDicIndexBetween(Integer value1, Integer value2) {
            addCriterion("dic_index between", value1, value2, "dicIndex");
            return (Criteria) this;
        }

        public Criteria andDicIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("dic_index not between", value1, value2, "dicIndex");
            return (Criteria) this;
        }

        public Criteria andDicKeyIsNull() {
            addCriterion("dic_key is null");
            return (Criteria) this;
        }

        public Criteria andDicKeyIsNotNull() {
            addCriterion("dic_key is not null");
            return (Criteria) this;
        }

        public Criteria andDicKeyEqualTo(String value) {
            addCriterion("dic_key =", value, "dicKey");
            return (Criteria) this;
        }

        public Criteria andDicKeyNotEqualTo(String value) {
            addCriterion("dic_key <>", value, "dicKey");
            return (Criteria) this;
        }

        public Criteria andDicKeyGreaterThan(String value) {
            addCriterion("dic_key >", value, "dicKey");
            return (Criteria) this;
        }

        public Criteria andDicKeyGreaterThanOrEqualTo(String value) {
            addCriterion("dic_key >=", value, "dicKey");
            return (Criteria) this;
        }

        public Criteria andDicKeyLessThan(String value) {
            addCriterion("dic_key <", value, "dicKey");
            return (Criteria) this;
        }

        public Criteria andDicKeyLessThanOrEqualTo(String value) {
            addCriterion("dic_key <=", value, "dicKey");
            return (Criteria) this;
        }

        public Criteria andDicKeyLike(String value) {
            addCriterion("dic_key like", value, "dicKey");
            return (Criteria) this;
        }

        public Criteria andDicKeyNotLike(String value) {
            addCriterion("dic_key not like", value, "dicKey");
            return (Criteria) this;
        }

        public Criteria andDicKeyIn(List<String> values) {
            addCriterion("dic_key in", values, "dicKey");
            return (Criteria) this;
        }

        public Criteria andDicKeyNotIn(List<String> values) {
            addCriterion("dic_key not in", values, "dicKey");
            return (Criteria) this;
        }

        public Criteria andDicKeyBetween(String value1, String value2) {
            addCriterion("dic_key between", value1, value2, "dicKey");
            return (Criteria) this;
        }

        public Criteria andDicKeyNotBetween(String value1, String value2) {
            addCriterion("dic_key not between", value1, value2, "dicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexIsNull() {
            addCriterion("mx_dic_index is null");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexIsNotNull() {
            addCriterion("mx_dic_index is not null");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexEqualTo(Integer value) {
            addCriterion("mx_dic_index =", value, "mxDicIndex");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexNotEqualTo(Integer value) {
            addCriterion("mx_dic_index <>", value, "mxDicIndex");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexGreaterThan(Integer value) {
            addCriterion("mx_dic_index >", value, "mxDicIndex");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("mx_dic_index >=", value, "mxDicIndex");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexLessThan(Integer value) {
            addCriterion("mx_dic_index <", value, "mxDicIndex");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexLessThanOrEqualTo(Integer value) {
            addCriterion("mx_dic_index <=", value, "mxDicIndex");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexIn(List<Integer> values) {
            addCriterion("mx_dic_index in", values, "mxDicIndex");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexNotIn(List<Integer> values) {
            addCriterion("mx_dic_index not in", values, "mxDicIndex");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexBetween(Integer value1, Integer value2) {
            addCriterion("mx_dic_index between", value1, value2, "mxDicIndex");
            return (Criteria) this;
        }

        public Criteria andMxDicIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("mx_dic_index not between", value1, value2, "mxDicIndex");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyIsNull() {
            addCriterion("mx_dic_key is null");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyIsNotNull() {
            addCriterion("mx_dic_key is not null");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyEqualTo(String value) {
            addCriterion("mx_dic_key =", value, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyNotEqualTo(String value) {
            addCriterion("mx_dic_key <>", value, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyGreaterThan(String value) {
            addCriterion("mx_dic_key >", value, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyGreaterThanOrEqualTo(String value) {
            addCriterion("mx_dic_key >=", value, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyLessThan(String value) {
            addCriterion("mx_dic_key <", value, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyLessThanOrEqualTo(String value) {
            addCriterion("mx_dic_key <=", value, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyLike(String value) {
            addCriterion("mx_dic_key like", value, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyNotLike(String value) {
            addCriterion("mx_dic_key not like", value, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyIn(List<String> values) {
            addCriterion("mx_dic_key in", values, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyNotIn(List<String> values) {
            addCriterion("mx_dic_key not in", values, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyBetween(String value1, String value2) {
            addCriterion("mx_dic_key between", value1, value2, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxDicKeyNotBetween(String value1, String value2) {
            addCriterion("mx_dic_key not between", value1, value2, "mxDicKey");
            return (Criteria) this;
        }

        public Criteria andMxValueIsNull() {
            addCriterion("mx_value is null");
            return (Criteria) this;
        }

        public Criteria andMxValueIsNotNull() {
            addCriterion("mx_value is not null");
            return (Criteria) this;
        }

        public Criteria andMxValueEqualTo(Integer value) {
            addCriterion("mx_value =", value, "mxValue");
            return (Criteria) this;
        }

        public Criteria andMxValueNotEqualTo(Integer value) {
            addCriterion("mx_value <>", value, "mxValue");
            return (Criteria) this;
        }

        public Criteria andMxValueGreaterThan(Integer value) {
            addCriterion("mx_value >", value, "mxValue");
            return (Criteria) this;
        }

        public Criteria andMxValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("mx_value >=", value, "mxValue");
            return (Criteria) this;
        }

        public Criteria andMxValueLessThan(Integer value) {
            addCriterion("mx_value <", value, "mxValue");
            return (Criteria) this;
        }

        public Criteria andMxValueLessThanOrEqualTo(Integer value) {
            addCriterion("mx_value <=", value, "mxValue");
            return (Criteria) this;
        }

        public Criteria andMxValueIn(List<Integer> values) {
            addCriterion("mx_value in", values, "mxValue");
            return (Criteria) this;
        }

        public Criteria andMxValueNotIn(List<Integer> values) {
            addCriterion("mx_value not in", values, "mxValue");
            return (Criteria) this;
        }

        public Criteria andMxValueBetween(Integer value1, Integer value2) {
            addCriterion("mx_value between", value1, value2, "mxValue");
            return (Criteria) this;
        }

        public Criteria andMxValueNotBetween(Integer value1, Integer value2) {
            addCriterion("mx_value not between", value1, value2, "mxValue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_mx_record
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 15 23:49:30 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_mx_record
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}