package com.artwook.nft.nftshop.db.model;

public class MxRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mx_record.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mx_record.record_id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mx_record.dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer dicIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mx_record.dic_key
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String dicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mx_record.mx_dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer mxDicIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mx_record.mx_dic_key
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String mxDicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mx_record.mx_value
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer mxValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mx_record.id
     *
     * @return the value of tb_mx_record.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mx_record.id
     *
     * @param id the value for tb_mx_record.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mx_record.record_id
     *
     * @return the value of tb_mx_record.record_id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mx_record.record_id
     *
     * @param recordId the value for tb_mx_record.record_id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mx_record.dic_index
     *
     * @return the value of tb_mx_record.dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getDicIndex() {
        return dicIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mx_record.dic_index
     *
     * @param dicIndex the value for tb_mx_record.dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setDicIndex(Integer dicIndex) {
        this.dicIndex = dicIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mx_record.dic_key
     *
     * @return the value of tb_mx_record.dic_key
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getDicKey() {
        return dicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mx_record.dic_key
     *
     * @param dicKey the value for tb_mx_record.dic_key
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setDicKey(String dicKey) {
        this.dicKey = dicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mx_record.mx_dic_index
     *
     * @return the value of tb_mx_record.mx_dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getMxDicIndex() {
        return mxDicIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mx_record.mx_dic_index
     *
     * @param mxDicIndex the value for tb_mx_record.mx_dic_index
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setMxDicIndex(Integer mxDicIndex) {
        this.mxDicIndex = mxDicIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mx_record.mx_dic_key
     *
     * @return the value of tb_mx_record.mx_dic_key
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getMxDicKey() {
        return mxDicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mx_record.mx_dic_key
     *
     * @param mxDicKey the value for tb_mx_record.mx_dic_key
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setMxDicKey(String mxDicKey) {
        this.mxDicKey = mxDicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mx_record.mx_value
     *
     * @return the value of tb_mx_record.mx_value
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getMxValue() {
        return mxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mx_record.mx_value
     *
     * @param mxValue the value for tb_mx_record.mx_value
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setMxValue(Integer mxValue) {
        this.mxValue = mxValue;
    }
}