package com.artwook.nft.nftshop.db.model;

import java.util.Date;

public class PathologyRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pathology_record.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pathology_record.pid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pathology_record.date
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pathology_record.pathology_type
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer pathologyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pathology_record.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pathology_record.updated_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pathology_record.pathology_data
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String pathologyData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pathology_record.id
     *
     * @return the value of tb_pathology_record.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pathology_record.id
     *
     * @param id the value for tb_pathology_record.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pathology_record.pid
     *
     * @return the value of tb_pathology_record.pid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pathology_record.pid
     *
     * @param pid the value for tb_pathology_record.pid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pathology_record.date
     *
     * @return the value of tb_pathology_record.date
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pathology_record.date
     *
     * @param date the value for tb_pathology_record.date
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pathology_record.pathology_type
     *
     * @return the value of tb_pathology_record.pathology_type
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getPathologyType() {
        return pathologyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pathology_record.pathology_type
     *
     * @param pathologyType the value for tb_pathology_record.pathology_type
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setPathologyType(Integer pathologyType) {
        this.pathologyType = pathologyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pathology_record.created_at
     *
     * @return the value of tb_pathology_record.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pathology_record.created_at
     *
     * @param createdAt the value for tb_pathology_record.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pathology_record.updated_at
     *
     * @return the value of tb_pathology_record.updated_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pathology_record.updated_at
     *
     * @param updatedAt the value for tb_pathology_record.updated_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pathology_record.pathology_data
     *
     * @return the value of tb_pathology_record.pathology_data
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getPathologyData() {
        return pathologyData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pathology_record.pathology_data
     *
     * @param pathologyData the value for tb_pathology_record.pathology_data
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setPathologyData(String pathologyData) {
        this.pathologyData = pathologyData;
    }
}