package com.artwook.nft.nftshop.db.model;

import java.util.Date;

public class Patient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_patient.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_patient.pid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_patient.name
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_patient.gender
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_patient.age
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_patient.hospital_no
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String hospitalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_patient.sickbed_no
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private String sickbedNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_patient.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_patient.id
     *
     * @return the value of tb_patient.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_patient.id
     *
     * @param id the value for tb_patient.id
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_patient.pid
     *
     * @return the value of tb_patient.pid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_patient.pid
     *
     * @param pid the value for tb_patient.pid
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_patient.name
     *
     * @return the value of tb_patient.name
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_patient.name
     *
     * @param name the value for tb_patient.name
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_patient.gender
     *
     * @return the value of tb_patient.gender
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_patient.gender
     *
     * @param gender the value for tb_patient.gender
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_patient.age
     *
     * @return the value of tb_patient.age
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_patient.age
     *
     * @param age the value for tb_patient.age
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_patient.hospital_no
     *
     * @return the value of tb_patient.hospital_no
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getHospitalNo() {
        return hospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_patient.hospital_no
     *
     * @param hospitalNo the value for tb_patient.hospital_no
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setHospitalNo(String hospitalNo) {
        this.hospitalNo = hospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_patient.sickbed_no
     *
     * @return the value of tb_patient.sickbed_no
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public String getSickbedNo() {
        return sickbedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_patient.sickbed_no
     *
     * @param sickbedNo the value for tb_patient.sickbed_no
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setSickbedNo(String sickbedNo) {
        this.sickbedNo = sickbedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_patient.created_at
     *
     * @return the value of tb_patient.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_patient.created_at
     *
     * @param createdAt the value for tb_patient.created_at
     *
     * @mbggenerated Mon Aug 15 23:49:30 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}